import { Icon, Logo } from "@stellar/design-system";
import { ComponentDetails, ComponentDetailsId } from "types/types";

export const assets: ComponentDetails = {
  id: ComponentDetailsId.assets,
  title: "Assets",
  description: `Collection of icon and logo assets.`,
  shortDescription:
    "Collection of icon and partner logo assets used across product and brand",
  examples: [
    {
      title: "Icons",
      description: <>SVG icon components, which are styled in CSS.</>,
      component: [
        <Icon.AccountBalanceWallet />,
        <Icon.AccountBalance />,
        <Icon.AccountCircle />,
        <Icon.AddCircle />,
        <Icon.Add />,
        <Icon.AllInbox />,
        <Icon.Anchor />,
        <Icon.Aod />,
        <Icon.ArrowCircleDown />,
        <Icon.ArrowCircleLeft />,
        <Icon.ArrowCircleRight />,
        <Icon.ArrowCircleUp />,
        <Icon.ArrowDown />,
        <Icon.ArrowLeft />,
        <Icon.ArrowRight />,
        <Icon.ArrowSmallDown />,
        <Icon.ArrowSmallLeft />,
        <Icon.ArrowSmallRight />,
        <Icon.ArrowSmallUp />,
        <Icon.ArrowTopLeft />,
        <Icon.ArrowTopRight />,
        <Icon.ArrowUp />,
        <Icon.Article />,
        <Icon.AttachFile />,
        <Icon.Attachment />,
        <Icon.Backspace />,
        <Icon.Backup />,
        <Icon.BarChart />,
        <Icon.Block />,
        <Icon.CalendarMonth />,
        <Icon.CalendarToday />,
        <Icon.ChatBubble />,
        <Icon.Chat />,
        <Icon.CheckCircle />,
        <Icon.Check />,
        <Icon.ChevronDoubleDown />,
        <Icon.ChevronDoubleLeft />,
        <Icon.ChevronDoubleRight />,
        <Icon.ChevronDoubleUp />,
        <Icon.ChevronDown />,
        <Icon.ChevronLeft />,
        <Icon.ChevronRight />,
        <Icon.ChevronUp />,
        <Icon.Clock />,
        <Icon.Close />,
        <Icon.CloudDone />,
        <Icon.CloudDownload />,
        <Icon.Code />,
        <Icon.ContactPage />,
        <Icon.Contacts />,
        <Icon.ContentCopy />,
        <Icon.ContentPaste />,
        <Icon.CopyAll />,
        <Icon.CurrencyExchange />,
        <Icon.Dashboard />,
        <Icon.DataArray />,
        <Icon.DataObject />,
        <Icon.Database />,
        <Icon.DeleteForever />,
        <Icon.Delete />,
        <Icon.Done />,
        <Icon.Download />,
        <Icon.Draft />,
        <Icon.Edit />,
        <Icon.Error />,
        <Icon.ExternalLink />,
        <Icon.Favorite />,
        <Icon.Filter />,
        <Icon.Flag />,
        <Icon.FolderCopy />,
        <Icon.Github />,
        <Icon.Grade />,
        <Icon.Help />,
        <Icon.History />,
        <Icon.Home />,
        <Icon.HourglassBottom />,
        <Icon.HourglassEmpty />,
        <Icon.HourglassFull />,
        <Icon.HourglassTop />,
        <Icon.Info />,
        <Icon.Insights />,
        <Icon.IosShare />,
        <Icon.Key />,
        <Icon.Layers />,
        <Icon.Link />,
        <Icon.LocalMall />,
        <Icon.LockOpen />,
        <Icon.Lock />,
        <Icon.Login />,
        <Icon.Logout />,
        <Icon.Mail />,
        <Icon.ManageSearch />,
        <Icon.Menu />,
        <Icon.ModeDark />,
        <Icon.ModeLight />,
        <Icon.MonetizationOn />,
        <Icon.MoreHoriz />,
        <Icon.MoreVert />,
        <Icon.Notifications />,
        <Icon.Password />,
        <Icon.Payments />,
        <Icon.Public />,
        <Icon.QrCode2 />,
        <Icon.QrCodeScanner />,
        <Icon.QrCode />,
        <Icon.Redeem />,
        <Icon.RefreshHoriz />,
        <Icon.RefreshVert />,
        <Icon.Replay />,
        <Icon.Search />,
        <Icon.Send />,
        <Icon.Settings />,
        <Icon.ShowChart />,
        <Icon.SignalCellularAlt />,
        <Icon.SortByAlpha />,
        <Icon.SpaceDashboard />,
        <Icon.StackedLineChart />,
        <Icon.Store />,
        <Icon.Toll />,
        <Icon.Tune />,
        <Icon.UnfoldLess />,
        <Icon.UnfoldMore />,
        <Icon.User />,
        <Icon.Users />,
        <Icon.VerifiedUser />,
        <Icon.Verified />,
        <Icon.VpnKey />,
        <Icon.Wallet />,
        <Icon.Warning />,
        <Icon.ZoomOutMap />,
      ],
      useGridLayout: true,
    },
    {
      title: "Logos",
      description:
        "SVG logo components, which can be styled in CSS if necessary.",
      component: [
        <Logo.Albedo />,
        <Logo.Freighter />,
        <Logo.Ledger />,
        <Logo.Stellar />,
        <Logo.Trezor />,
      ],
      useGridLayout: true,
    },
  ],
  props: [],
  externalProps: {
    link: "",
    label: "",
  },
};
